In [1]:
from google.colab import drive
drive.mount('/content/drive')
!pip install "drive/MyDrive/Master Data Science/TFM/GITHUB/modelado_multidimensional_engagement-0.1.0-py3-none-any.whl"

Mounted at /content/drive
Processing ./drive/MyDrive/Master Data Science/TFM/GITHUB/modelado_multidimensional_engagement-0.1.0-py3-none-any.whl
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (1.16.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->modelado-multidimensional-engagement==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->modelado-multidimensional-engagement==0.1.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->modelado-multidimensional-engagement==0.1.0) (1.17.0)
Installing collected packages: modelado-multidimensional-engagement
Successfully installed modelado-multidimensional-engagement-0.1.0

In [2]:
from src.evaluation.kpis_analysis import (
    compute_cluster_kpi_reports,
    compute_category_elasticity_reports,
    _load_month,
    compute_category_elasticity_summary
)
import src.config as config
import os
import pandas as pd
config.WORKPATH

'drive/MyDrive/Master Data Science/TFM/GITHUB'

In [3]:
clusters = pd.read_parquet(os.path.join(config.RESULTSPATH, "clusters", "training_clusters.parquet"))

In [4]:
clusters

,category_code,cluster_generic,cluster_user_based,cluster_time_based,category_base
0,electronics.smartphone,0,3,1,electronics
1,appliances.sewing_machine,1,1,3,appliances
2,appliances.kitchen.washer,0,3,1,appliances
3,computers.notebook,0,3,1,computers
4,furniture.living_room.sofa,0,3,1,furniture
...,...,...,...,...,...
124,apparel.glove,1,2,0,apparel
125,apparel.skirt,2,2,2,apparel
126,apparel.jacket,1,2,3,apparel
127,appliances.kitchen.fryer,2,2,2,appliances
128,construction.tools.screw,1,2,1,construction

In [ ]:
df_dec = _load_month("Dec")
df_nov = _load_month("Nov")
cluster_generic, cluster_user_based, cluster_time_based = compute_cluster_kpi_reports(df_nov, df_dec)

In [5]:
cluster_generic, cluster_user_based, cluster_time_based = (
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "cluster_generic.parquet")),
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "cluster_user_based.parquet")),
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "cluster_time_based.parquet"))
)

In [7]:
cluster_generic

  temporalidad  cluster_generic  precio_prom  compras  conversion_prom
0          DEC                0   280.398619   305208         0.017814
1          DEC                1   187.740981   155726         0.019288
2          DEC                2   357.916795   536932         0.033416
3          NOV                0   375.447260   593269         0.022417
4          NOV                1   206.587619    35654         0.014467
5          NOV                2    81.567433     6804         0.008223

In [8]:
cluster_user_based

  temporalidad  cluster_user_based  precio_prom  compras  conversion_prom
0          DEC                   0   338.601597   544463         0.031521
1          DEC                   1   188.639540    58268         0.014472
2          DEC                   2   248.318028   123354         0.025071
3          DEC                   3   315.845040   206326         0.018351
4          DEC                   4   180.940167    65455         0.017171
5          NOV                   0    98.950968    35839         0.011825
6          NOV                   1   237.559057    36830         0.014285
7          NOV                   2   224.999412     1383         0.007590
8          NOV                   3   411.208868   544380         0.023794
9          NOV                   4   139.401254    17295         0.015909

In [9]:
cluster_time_based

  temporalidad  cluster_time_based  precio_prom  compras  conversion_prom
0          DEC                   0   379.236878   520677         0.033551
1          DEC                   1   243.900372   294853         0.018796
2          DEC                   2   227.806843   125579         0.019569
3          DEC                   3   245.787660    56757         0.015544
4          NOV                   0   133.560177    24011         0.012472
5          NOV                   1   423.665092   513455         0.023051
6          NOV                   2   156.030790    37571         0.012689
7          NOV                   3   137.390284    60690         0.023378

In [ ]:
compras, eventos, conversion_mes = compute_category_elasticity_reports(df_dec=df_dec, df_nov=df_nov)

In [10]:
compras, eventos, conversion_mes = (
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "compras.parquet")),
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "eventos.parquet")),
    pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "conversion_mes.parquet"))
)

In [11]:
compras

                     precio_prom             compras         elasticidad
temporalidad                 DEC         NOV     DEC     NOV
category_code
accessories.bag        74.742381   68.552029  3737.0  1711.0   13.112769
accessories.umbrella  364.739627   19.340099   230.0    26.0    0.439333
accessories.wallet    112.552078   60.592364  3054.0   347.0    9.097246
apparel.belt           41.194206   52.803147    75.0    40.0   -3.979928
apparel.costume       160.915259  102.241872  4953.0   848.0    8.435386
...                          ...         ...     ...     ...         ...
sport.ski             131.521953  338.047933  6923.0    67.0 -167.494133
sport.snowboard       189.731041  257.985256   440.0   131.0   -8.915641
sport.tennis          171.347346   58.269254   497.0    46.0    5.052190
sport.trainer         224.089216  362.024105  3884.0   651.0  -13.034311
stationery.cartrige   107.386738   34.025625   439.0   188.0    0.619236

[135 rows x 5 columns]

In [12]:
eventos

    temporalidad         category_code event_type  conteo
0            DEC       accessories.bag       cart   10147
1            DEC       accessories.bag   purchase    3737
2            DEC       accessories.bag       view  399868
3            DEC  accessories.umbrella       cart     727
4            DEC  accessories.umbrella   purchase     230
..           ...                   ...        ...     ...
780          NOV         sport.trainer   purchase     651
781          NOV         sport.trainer       view   55941
782          NOV   stationery.cartrige       cart     483
783          NOV   stationery.cartrige   purchase     188
784          NOV   stationery.cartrige       view    7734

[785 rows x 4 columns]

In [13]:
conversion_mes

    temporalidad         category_code  conversion
0            DEC       accessories.bag    0.009032
1            DEC  accessories.umbrella    0.005517
2            DEC    accessories.wallet    0.014620
3            DEC          apparel.belt    0.011704
4            DEC       apparel.costume    0.015241
..           ...                   ...         ...
259          NOV             sport.ski    0.005981
260          NOV       sport.snowboard    0.009833
261          NOV          sport.tennis    0.008772
262          NOV         sport.trainer    0.011126
263          NOV   stationery.cartrige    0.022368

[264 rows x 3 columns]

In [15]:
clusters.columns

Index(['category_code', 'cluster_generic', 'cluster_user_based',
       'cluster_time_based', 'category_base'],
      dtype='object')

In [16]:
compras_reset = compras.reset_index(drop=False).reset_index(drop=False)
compras_reset.columns = [
    f"{col[0]}_{col[1]}" if col[1] != '' else col[0]
    for col in compras_reset.columns
]

In [17]:
compras_reset

,index,category_code,precio_prom_DEC,precio_prom_NOV,compras_DEC,compras_NOV,elasticidad
0,0,accessories.bag,74.742381,68.552029,3737.0,1711.0,13.112769
1,1,accessories.umbrella,364.739627,19.340099,230.0,26.0,0.439333
2,2,accessories.wallet,112.552078,60.592364,3054.0,347.0,9.097246
3,3,apparel.belt,41.194206,52.803147,75.0,40.0,-3.979928
4,4,apparel.costume,160.915259,102.241872,4953.0,848.0,8.435386
...,...,...,...,...,...,...,...
130,130,sport.ski,131.521953,338.047933,6923.0,67.0,-167.494133
131,131,sport.snowboard,189.731041,257.985256,440.0,131.0,-8.915641
132,132,sport.tennis,171.347346,58.269254,497.0,46.0,5.052190
133,133,sport.trainer,224.089216,362.024105,3884.0,651.0,-13.034311
134,134,stationery.cartrige,107.386738,34.025625,439.0,188.0,0.619236

In [18]:
compute_category_elasticity_summary(compras_reset, clusters)

(     level_0  index         category_code  precio_prom_DEC  precio_prom_NOV  \
 0          0      0       accessories.bag        74.742381        68.552029
 1          1      1  accessories.umbrella       364.739627        19.340099
 2          2      2    accessories.wallet       112.552078        60.592364
 3          3      3          apparel.belt        41.194206        52.803147
 4          4      4       apparel.costume       160.915259       102.241872
 ..       ...    ...                   ...              ...              ...
 130      130    130             sport.ski       131.521953       338.047933
 131      131    131       sport.snowboard       189.731041       257.985256
 132      132    132          sport.tennis       171.347346        58.269254
 133      133    133         sport.trainer       224.089216       362.024105
 134      134    134   stationery.cartrige       107.386738        34.025625

      compras_DEC  compras_NOV  elasticidad  cluster_generic  \
 0         3737.0       1711.0    13.112769              0.0
 1          230.0         26.0     0.439333              2.0
 2         3054.0        347.0     9.097246              0.0
 3           75.0         40.0    -3.979928              1.0
 4         4953.0        848.0     8.435386              0.0
 ..           ...          ...          ...              ...
 130       6923.0         67.0  -167.494133              1.0
 131        440.0        131.0    -8.915641              1.0
 132        497.0         46.0     5.052190              1.0
 133       3884.0        651.0   -13.034311              0.0
 134        439.0        188.0     0.619236              1.0

      cluster_user_based  cluster_time_based category_base  \
 0                   0.0                 0.0   accessories
 1                   2.0                 0.0   accessories
 2                   4.0                 1.0   accessories
 3                   2.0                 0.0       apparel
 4                   0.0                 0.0       apparel
 ..                  ...                 ...           ...
 130                 4.0                 1.0         sport
 131                 4.0                 1.0         sport
 132                 4.0                 0.0         sport
 133                 4.0                 1.0         sport
 134                 1.0                 0.0    stationery

      elastico_no_elastico
 0                       1
 1                       0
 2                       1
 3                       0
 4                       1
 ..                    ...
 130                     0
 131                     0
 132                     1
 133                     0
 134                     0

 [112 rows x 13 columns],
    cluster_generic  elastico_no_elastico       mean         std    median  \
 0              0.0                     0  -3.192163    3.840914 -1.713867
 1              0.0                     1  13.009217   30.274236  4.622481
 2              1.0                     0 -30.146383   80.246577 -4.585857
 3              1.0                     1  10.279189   10.535015  7.039570
 4              2.0                     0  -2.142386    5.347920 -0.115070
 5              2.0                     1  77.743625  148.205181  9.723199

           min         max  count
 0  -13.586623    0.771219     25
 1    1.000247  131.703309     18
 2 -414.601721    0.686773     32
 3    1.031525   40.779180     16
 4  -16.134229    0.660709      9
 5    1.380194  516.723048     12  )

In [ ]:
from src.evaluation.gmv import compute_category_gmv_summary


summary_df = compute_category_gmv_summary(
    config.WORKPATH,
    source_folder="training_201911",
    category_codes=config.CATEGORY_CODES,
    output_path=os.path.join(config.RESULTSPATH, "validation_analysis", "training_GMV.parquet"),
    show_progress=False
)

summary_df = compute_category_gmv_summary(
    config.WORKPATH,
    source_folder="training_201911",
    category_codes=config.CATEGORY_CODES,
    output_path=os.path.join(config.RESULTSPATH, "validation_analysis", "evaluation_GMV.parquet"),
    show_progress=False
)

In [20]:
summary_df

,category_code,average_price,view_to_cart_rate,cart_to_purchase_rate,total_purchase_probability,expected_gmv
0,electronics.smartphone,499.453047,0.078938,0.462251,0.032713,1.640188e+08
1,appliances.sewing_machine,253.853970,0.049243,0.366158,0.016894,5.743125e+05
2,appliances.kitchen.washer,341.155409,0.057102,0.417215,0.022040,5.433262e+06
3,computers.notebook,742.316918,0.032476,0.408899,0.012698,9.952211e+06
4,furniture.living_room.sofa,642.607242,0.016672,0.323980,0.005285,8.293002e+05
...,...,...,...,...,...,...
253,apparel.glove,59.412843,0.046208,0.332609,0.014478,9.687300e+03
254,apparel.skirt,143.238876,0.020223,0.364407,0.007171,6.674220e+03
255,apparel.jacket,149.999155,0.030149,0.345679,0.010016,7.316710e+03
256,appliances.kitchen.fryer,99.753071,0.025077,0.318766,0.007738,1.058479e+04
257,construction.tools.screw,275.204103,0.018428,0.366142,0.006582,4.054999e+04

In [ ]:
from src.evaluation.absence_time import compute_absence_time_summary

summary_absence_time_nov = compute_absence_time_summary(
    config.WORKPATH,
    source_folder="training_201911",
    category_codes=config.CATEGORY_CODES,
    output_path=os.path.join(config.RESULTSPATH, "validation_analysis", "training_AbsenseTime.parquet"),
    show_progress=False
)
summary_absence_time_dec = compute_absence_time_summary(
    config.WORKPATH,
    source_folder="validation_201912",
    category_codes=config.CATEGORY_CODES,
    output_path=os.path.join(config.RESULTSPATH, "validation_analysis", "evaluation_AbsenseTime.parquet"),
    show_progress=False
)

In [48]:
summary_absence_time_nov = pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "training_AbsenseTime.parquet"))
summary_absence_time_dec = pd.read_parquet(os.path.join(config.RESULTSPATH, "validation_analysis", "evaluation_AbsenseTime.parquet"))
cluster_user_based_nov = pd.read_parquet(os.path.join(config.RESULTSPATH, "clusters", "training_user_clusters.parquet"))
cluster_user_based_dec = pd.read_parquet(os.path.join(config.RESULTSPATH, "clusters", "validation_user_clusters.parquet"))

In [49]:
cols = ["category_code", "cluster"]
summary_absence_time_nov = summary_absence_time_nov.merge(cluster_user_based_nov[cols], on="category_code", how="left").rename(columns={"cluster": "user_based_nov"})
summary_absence_time_nov = summary_absence_time_nov.merge(cluster_user_based_dec[cols], on="category_code", how="left").rename(columns={"cluster": "user_based_dic"})

comparison = summary_absence_time_nov.merge(summary_absence_time_dec, on="category_code", how="left", suffixes=('_nov','_dic'))
comparison['absence_drop'] = comparison['absence_time_mean_dic'] - comparison['absence_time_mean_nov']

df_clean = comparison.drop_duplicates(subset=['category_code', 'absence_time_mean_dic'], keep='last')
df_clean = df_clean.reset_index(drop=True)

df_clean['cluster'] = df_clean['user_based_dic']

In [50]:
cluster_summary = df_clean.groupby('cluster').agg({
    'absence_time_mean_nov': 'mean',
    'absence_time_mean_dic': 'mean',
    'absence_drop': 'mean'
})
cluster_summary

         absence_time_mean_nov  absence_time_mean_dic  absence_drop
cluster
0                     0.572942               0.571084     -0.001859
1                     0.440771               0.539530      0.098759
2                     0.414132               0.595560      0.181429
3                     0.420994               0.628724      0.201868
4                     0.407622               0.508418      0.100796

In [51]:
urgent_categories = df_clean[df_clean['absence_drop'] < 0].sort_values('absence_drop')
urgent_categories[['category_code','absence_drop','cluster']]

                    category_code  absence_drop  cluster
237     apparel.shoes.espadrilles     -0.545417        0
221      electronics.camera.photo     -0.503979        0
227  construction.tools.soldering     -0.405594        3
17    electronics.audio.headphone     -0.239810        4
219  auto.accessories.anti_freeze     -0.188040        3
23       electronics.camera.video     -0.121705        4
145                   kids.skates     -0.076371        4
199       country_yard.cultivator     -0.066658        3
173      appliances.kitchen.grill     -0.040596        1
149      appliances.kitchen.mixer     -0.003748        1

In [53]:
categorias_top10 = [
    "electronics.smartphone",
    "electronics.video.tv",
    "computers.notebook",
    "electronics.clocks",
    "apparel.shoes",
    "electronics.audio.headphone",
    "appliances.environment.vacuum",
    "appliances.kitchen.refrigerators",
    "appliances.kitchen.washer",
    "computers.desktop"
]

summary_absence_time_nov[summary_absence_time_nov["category_code"].isin(categorias_top10)]

,category_code,absence_time_mean,user_based_nov,user_based_dic
0,electronics.smartphone,0.549214,3,4
2,appliances.kitchen.washer,0.406889,3,4
3,computers.notebook,0.318747,3,4
5,appliances.kitchen.refrigerators,0.362573,3,4
8,electronics.audio.headphone,0.795454,3,4
9,appliances.environment.vacuum,0.396526,3,4
12,electronics.clocks,0.511505,3,4
13,electronics.video.tv,0.484082,3,4
20,computers.desktop,0.385067,3,4
30,apparel.shoes,0.301529,3,4

In [58]:
import json

cluster_data = df_clean.groupby('cluster')['absence_drop'].apply(list).to_dict()
data_json = json.dumps({str(k): v for k, v in cluster_data.items()})

html = f"""<!-- reemplaza clusterData con: -->
const clusterData = {data_json};
"""
print(html)

<!-- reemplaza clusterData con: -->
const clusterData = {"0": [0.0, 0.12307620533291003, 0.0, 0.1574260649378978, 0.0, 0.5124858950561789, 0.0, 0.025386490275363993, 0.0, 0.2050014729159947, 0.0, -0.5039785148627924, 0.0, -0.5454166621567502], "1": [0.0, 0.030908019840332424, 0.0, 0.5002471131450875, 0.0, 0.36107880867795517, 0.0, 0.203565809639703, 0.0, 0.4264792156441973, 0.0, 0.02727484549096304, 0.0, 0.395175073721509, 0.0, 0.21881263761806996, 0.0, 0.1402994332587632, 0.0, 0.07105026021230387, 0.0, 0.10153549665398365, 0.0, 0.18278717568008995, 0.0, 0.6540948353322271, 0.0, 0.06628427306140994, 0.0, -0.0037478079996688396, 0.0, 0.17930093613570303, 0.0, 0.014032549497734359, 0.0, 0.22087070999036512, 0.0, 0.0146010812565453, 0.0, 0.0708014381230252, 0.0, -0.040596282988942356, 0.0, 0.20059375901440607, 0.0, 0.3233526514361763, 0.0, 0.24356512982184225, 0.0, 0.335564985306861], "2": [0.0, 0.34500311749533735, 0.0, 0.4204446932150303, 0.0, 0.6818099222784955, 0.0, 0.1953371426056788, 0.0, 0.3958253026578722, 0.0, 0.42151244133431454, 0.0, 0.4759434397253639, 0.0, 0.3309336132920051, 0.0, 0.1553144864802457, 0.0, 0.4092092293085224, 0.0, 0.44040222742139384, 0.0, 0.2849147070095481, 0.0, 0.22621822396506214, 0.0, 0.29713551826167106], "3": [0.0, 0.36882428871651884, 0.0, 0.2246204474212128, 0.0, 0.2738245213521919, 0.0, 0.6258263994795776, 0.0, 0.6639701414856214, 0.0, 1.0491033016873021, 0.0, 0.495237215325802, 0.0, 0.3851044829987136, 0.0, 0.3639193020877285, 0.0, 0.927672815991482, 0.0, 0.26597641151415674, 0.0, 0.7567547593629371, 0.0, 0.4581919197446792, 0.0, 0.14370982921422487, 0.0, 0.3175609553091766, 0.0, 0.16199065479667113, 0.0, 0.07844839665656345, 0.0, 0.5280018301509949, 0.0, -0.06665838252725687, 0.0, 0.6974188615172598, 0.0, 0.15445002325837903, 0.0, -0.18803991836273215, 0.0, 0.42935184986928016, 0.0, 0.3389515545386094, 0.0, -0.40559384139577104, 0.0, 0.35324008846184424, 0.0, 0.23918761484968953, 0.0, 0.36804551958748444, 0.0, 0.491415356646348, NaN, 0.0, 0.49764961920908163, 0.0, 0.7914141897350853, NaN, NaN, 0.0, 0.7480097979179424, 0.0, 0.7857263943041194], "4": [0.0, 0.8557263034343908, 0.0, 0.06217353795370939, 0.0, 0.026897939115978264, 0.0, 0.3833963026798729, 0.0, 0.06808287597962698, 0.0, 0.38860221097313413, 0.0, 0.13504790048439513, 0.0, -0.23980995928819748, 0.0, 0.0762421169848076, 0.0, -0.12170527252965674, 0.0, 0.07877171723345122, 0.0, 0.1769758077642697, 0.0, 0.32152301076017836, 0.0, 0.006502129910389287, 0.0, 0.1679125560964192, 0.0, 0.47224683716186006, 0.0, 0.2986010243146234, 0.0, 0.06805905648241906, 0.0, 0.03314425826843809, 0.0, 0.21990486860142783, 0.0, 0.03244387118456693, 0.0, 0.6133102619764117, 0.0, 0.21738781079566433, 0.0, 0.3174846027835077, 0.0, 0.21870638139686788, 0.0, 0.29269298914664765, 0.0, 0.22090207194727235, 0.0, 0.11704614963577609, 0.0, 0.3232753008051657, 0.0, 0.19827140411321875, 0.0, 0.021408221279699435, 0.0, 0.40981957743119196, 0.0, 0.3517593741114562, 0.0, 0.02593033946872947, 0.0, -0.07637139707471857, 0.0, 0.23318756022494147, 0.0, 0.17498183560948327, 0.0, 0.02748377820728687, 0.0, 0.25206043126790834, 0.0, 0.007521563267314124, 0.0, 0.15525555576189087, 0.0, 0.3047211062149061, 0.0, 0.38839371022504626, 0.0, 0.17375478642519326, 0.0, 0.46778442236475865, 0.0, 0.19317542863585968, 0.0, 0.236889150926953, 0.0, 0.2988183744284582]};